#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "com.crowdproj.resources.app.ApplicationJvmKt.moduleJvm"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"

resources:
  repository:
    test: "inmemory"
    prod: "psql"
    # prod: cassandra
    psql:
      password: "postgres"
      schema: "resources"
      url: "jdbc:postgresql://localhost:5432/resources"
      user: "postgres"
