# Minimum version of the infrastructure based on
# Fluent Bit - collects, processes and sends log messages to the storage.
# OpenSearch - centrally stores log messages, provides their quick search and filtering.
# OpenSearch Dashboards - provides an interface to the user to visualize the data stored in opensearch

version: "3"
services:

  app:
    container_name: app
    image: nginx
    ports:
      - 8080:80
    volumes:
      # adding the configuration to the container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fluent-bit
    logging:
      # the logging driver used
      driver: "fluentd"
      options:
        # where to send log messages
        # it is necessary that the address matches the settings of the forward plugin
        fluentd-address: localhost:24224
        # tags are used to route log messages
        tag: app.logs
    networks:
      - opensearch

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      # it is necessary to open the ports that are used by the forward plugin
      - 24224:24224
      - 24224:24224/udp
      - 2020:2020
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=admin
    volumes:
      # adding the configuration to the container
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    networks:
      - opensearch

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - opensearch

volumes:
  opensearch-data:

networks:
  opensearch:
    driver: bridge