openapi: 3.0.4
info:
  title: Resources log models
  description: Log models for logging services resources of marketplace
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        resource:
          $ref: '#/components/schemas/ResourceLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    ResourceLogModel:
      title: Модель лога для микросервиса Marketplace
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - init
            - finish
        requestAd:
          $ref: '#/components/schemas/ResourceLog'
        requestFilter:
          $ref: '#/components/schemas/ResourceFilterLog'
        responseAd:
          $ref: '#/components/schemas/ResourceLog'
        responseAds:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    ResourceLog:
      title: Модель лога для ресурсов
      type: object
      properties:
        id:
          type: string
        resourcesId:
          type: string
        scheduleId:
          type: string
        visible:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    ResourceFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string